### ISSUE TITLE
Installing Sirius 

### ISSUE THREAD

**Issue by geocontrol** [genmon/sirius#16]
Hi, Rather than clutter up other threads, here is where we can post any problems we are finding in trying to get the server installed and talking to our little printers. 

I have tried to follow the instructions from https://github.com/genmon/sirius/issues/10#issuecomment-137790280 (posted by https://github.com/bskrt) with some initial success in that it appeared to install and run, but when i tried to print I got an internal server error (I am trying to find the log files). Anyway I just tried to kill services on the RPi and it is now no longer starting:

mark@ethpi:~/sirius$ gunicorn -b 0.0.0.0:5000 -k flask_sockets.worker manage:app
[2016-01-18 20:32:35 +0000] [22738] [INFO] Starting gunicorn 19.4.5
[2016-01-18 20:32:35 +0000] [22738] [INFO] Listening at: http://0.0.0.0:5000 (22738)
[2016-01-18 20:32:35 +0000] [22738] [INFO] Using worker: flask_sockets.worker
[2016-01-18 20:32:35 +0000] [22738] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 180, in run
    self.manage_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 482, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 548, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 502, in spawn_worker
    self.cfg, self.log)
TypeError: 'str' object is not callable

Which is all rather annoying. I am not very up on python though. Any thoughts?

**Comment by geocontrol** [comment]
Actually i'm closing this as there is a thread already open to discuss installing issues

**Comment by amcewen** [comment]
I presume that the "thread already open to discuss installing issues" is issue #15 (mostly adding this comment to let others find that more easily in future if they get here first :-)
